/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ../../raw-assets/plastic_monobloc_chair_01_1k.gltf --types --transform --root /public/model --output ../../src/Chair.tsx
*/
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    plastic_monobloc_chair_01: THREE.Mesh
  }
  materials: {
    plastic_monobloc_chair_01: THREE.MeshStandardMaterial
  }
}

export function Chair(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    'model/plastic_monobloc_chair_01_1k-transformed.glb'
  ) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.plastic_monobloc_chair_01.geometry}
        material={materials.plastic_monobloc_chair_01}
      />
    </group>
  )
}

useGLTF.preload('model/plastic_monobloc_chair_01_1k-transformed.glb')
