/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/gnome/garden_gnome_1k.gltf --types --transform --printwidth 80 -r gnome -o src/GnomeT.tsx
*/
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    garden_gnome: THREE.Mesh
  }
  materials: {
    garden_gnome_01: THREE.MeshStandardMaterial
  }
}

export function Gnome(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    'model/garden_gnome_1k-transformed.glb'
  ) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.garden_gnome.geometry}
        material={materials.garden_gnome_01}
      />
    </group>
  )
}

useGLTF.preload('model/garden_gnome_1k-transformed.glb')
