/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/gf-clock/vintage_grandfather_clock_01_1k.gltf --types --printwidth80 -r public -o src/Grandfather.tsx
*/
import { useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder001: THREE.Mesh
    Cylinder001_1: THREE.Mesh
    vintage_grandfather_clock_01_minute_hand: THREE.Mesh
    vintage_grandfather_clock_01_houd_hand: THREE.Mesh
  }
  materials: {
    vintage_grandfather_clock_01: THREE.MeshStandardMaterial
    vintage_grandfather_clock_01_glass: THREE.MeshPhysicalMaterial
  }
}

export function Grandfather(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/gf-clock/vintage_grandfather_clock_01_1k.gltf'
  ) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.063, 0, -0.063]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          geometry={nodes.Cylinder001.geometry}
          material={materials.vintage_grandfather_clock_01}
        />
        <mesh
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.vintage_grandfather_clock_01_glass}
        />
      </group>
      <mesh
        geometry={nodes.vintage_grandfather_clock_01_minute_hand.geometry}
        material={materials.vintage_grandfather_clock_01}
        position={[0.063, 1.732, 0.063]}
        rotation={[0.007, -0.073, -0.356]}
      />
      <mesh
        geometry={nodes.vintage_grandfather_clock_01_houd_hand.geometry}
        material={materials.vintage_grandfather_clock_01}
        position={[0.063, 1.732, 0.063]}
      />
    </group>
  )
}

useGLTF.preload('/gf-clock/vintage_grandfather_clock_01_1k.gltf')
