/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ../../raw-assets/food_lime_01_1k.gltf --types --transform --root /public/model --output ../../src/Lime.tsx
*/
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    food_lime_01: THREE.Mesh
  }
  materials: {
    food_lime_01: THREE.MeshStandardMaterial
  }
}

export function Lime(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('model/food_lime_01_1k-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.food_lime_01.geometry} material={materials.food_lime_01} />
    </group>
  )
}

useGLTF.preload('model/food_lime_01_1k-transformed.glb')
